builds:
  - main: ./starport/interface/cli/starport
    ldflags:
      - -s -w -X github.com/tendermint/starport/starport/internal/version.Version={{.Tag}} -X github.com/tendermint/starport/starport/internal/version.Date={{.Date}}

brews:
  - name: "starport"
    description: "CLI tool for developing Cosmos SDK apps."
    homepage: "https://github.com/tendermint/starport"
    github:
      owner: "tendermint"
      name: "homebrew-tap"
    install: |
      bin.install "starport"
