builds:
  - main: ./starport/interface/cli/starport

brews:
  - name: "starport"
    description: "CLI tool for developing Cosmos SDK apps."
    homepage: "https://github.com/tendermint/starport"
    github:
      owner: "tendermint"
      name: "homebrew-tap"
    install: |
      bin.install "starport"
