# This workflow makes a 64 bit Raspberry Pi Arch Linux Image.
# It does not have the security issues mentioned here: https://github.com/tendermint/tendermint/blob/master/docs/tendermint-core/running-in-production.md#validator-signing-on-32-bit-architectures-or-arm
# Later, more devices will be supported, as well.
# The "base" is built by: https://github.com/faddat/sos
# The base image is located at: https://hub.docker.com/r/faddat/spos

name: Pi Image
on: [push, pull_request]

jobs:
  build:
    name: Starport Pi Image
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        working-directory: .pi
        run: bash build.sh
  
      - name: Compress
        working-directory: .pi
        run: |
          sudo apt install -y pbzip2
          pbzip2 images/starport.img
      
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: .pi/images/starport.img.bz2
