name: Pi Image
on: [push, pull_request]

jobs:
  build:
    name: Starport Pi Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build starport.img with packer-builder-arm
        run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build images/starport.json
        
      - name: Upload artifacts  
        uses: actions/upload-artifact@v2
        with:
          name: Starport PI
          path: starport.img
