# run unit tests for Starport.
name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: install
        run: make install
      - name: test
        run: ./scripts/test-unit 
